### ISSUE TITLE
Playing stream not showing

### ISSUE THREAD

**Issue by nkijak** [jmowbray/rdio-remote#2]
![screen shot 2015-04-29 at 12 35 20 pm](https://cloud.githubusercontent.com/assets/601071/7396085/48e2f73c-ee6c-11e4-87e3-c6b1fc2867d5.png)
- Web Store install
- Uninstalled Exploded version
- Opened extension
- Clicked play something -> taken to Rdio tab
- Start playing in Rdio
- Next track in Rdio

**Comment by nkijak** [comment]
Removed the Web Store one and re-installed.  Now it works.  Dunno.

**Comment by jmowbray** [comment]
Was the Rdio tab open already open when you installed it? I think that refreshing the Rdio tab would fix it in that situation.

The extension needs to inject to the content script when that page loads, but if that page was already loaded when the extension is installed, it won't know to report back to the extension that it's a viable tab.

Perhaps hooks during installation could fix this, if the extension API has such a thing. Or as part of the "play something" logic, if there is already a tab open we're activating, to force a refresh.

**Comment by nkijak** [comment]
I did try refreshing Rdio.  Forgot to mention that step.

**Comment by jmowbray** [comment]
The manifest was wrong. It only worked for url's the explicitly ended in `rdio.com/` instead of `rdio.com/*` which is why you got that on your user page.

Fixed in a31edbdfca3f264c5396b6a83e77a8b9df81cef3 The update package was uploaded to the chrome web store.
